//! One module per instrument. Every view takes data and a theme and knows
//! nothing else.

pub mod ask;
pub mod chrome;
pub mod codex;
pub mod cogitator;
pub mod compact;
pub mod diff;
pub mod disegno;
pub mod export;
pub mod governor;
pub mod grafo;
pub mod graph_run;
pub mod highlight;
pub mod instrumenta;
pub mod keys;
pub mod login;
pub mod markdown;
pub mod memoria;
pub mod mensura;
pub mod officina;
pub mod opera;
pub mod recovery;
pub mod resume;
pub mod securitas;
pub mod settings;
pub mod startup;
pub mod studio;
pub mod thinking;
pub mod transcript;
pub mod tree;
pub mod trust;
pub mod vectors;
