// Generated by scripts/design-contracts.py from Rust DTO declarations. Do not edit.
export type SchemaVersion = 1;
export type RevisionId = string;
export type ArtifactId = string;
export type VariantId = string;
export type ArtboardId = string;
export type NodeId = string;
export type CommentId = string;
export type OperationId = string;
export type DesignKind = "landing" | "product" | "document";
export interface SourceBundle { files: Record<string, ArtifactRef>; entry_points: Array<string> }
export interface Artboard { id: ArtboardId; title: string; entry_point: string }
export interface Variant { id: VariantId; title: string; artboards: Array<Artboard> }
export interface ArtifactRef { id: string; sha256: string; media_type: string; size: string; relative_store_path: string; redaction: string | null }
export interface CreateDesign { title: string; brief: string; kind: DesignKind; operation_id: OperationId; variants: number }
export interface ArtifactManifest { schema_version: SchemaVersion; id: ArtifactId; owner_session: string; workspace: string; branch_entry: string | null; title: string; kind: DesignKind; brief: ArtifactRef; requested_variants: number; created_at_ms: string; revision: RevisionId; ancestry: RevisionReference | null }
export interface RevisionReference { artifact_id: ArtifactId; revision: RevisionId; source_hash: string }
export interface DesignRevision { schema_version: SchemaVersion; artifact_id: ArtifactId; revision: RevisionId; parent: RevisionId; operation_id: OperationId; source_hash: string; sources: SourceBundle; variants: Array<Variant>; bindings: Array<EditableBinding>; assets: Array<Asset>; profile_refs: Array<ArtifactRef>; system_snapshot: ArtifactRef | null; restored_from: RevisionId | null }
export interface RevisionWrite { artifact_id: ArtifactId; expected_revision: RevisionId; operation_id: OperationId; sources: SourceBundle; variants: Array<Variant>; bindings: Array<EditableBinding>; assets: Array<Asset>; profile_refs: Array<ArtifactRef>; system_snapshot: ArtifactRef | null }
export interface EditableBinding { node_id: NodeId; artboard_id: ArtboardId; source_file: string; source_hash: string; pointer: string; constraint: BindingConstraint; affected_nodes: Array<NodeId> }
export type BindingConstraint = { type: "text"; max_bytes: number } | { type: "enum"; values: Array<string> } | { type: "number"; min: number; max: number } | { type: "color";  } | { type: "local_asset"; paths: Array<string> };
export interface Asset { path: string; source: ArtifactRef; provenance: string; rights: string; width: number; height: number }
export interface DesignEdit { artifact_id: ArtifactId; expected_revision: RevisionId; node_id: NodeId; expected_binding_hash: string; operation_id: OperationId; value: unknown; confirmed_affected_nodes: Array<NodeId> }
export interface DesignComment { id: CommentId; artifact_id: ArtifactId; revision: RevisionId; artboard_id: ArtboardId; node_id: NodeId | null; x_milli: number; y_milli: number; text: string }
export interface Viewport { width: number; height: number }
export interface RenderRequest { artifact_id: ArtifactId; revision: RevisionId; artboard_id: ArtboardId; viewport: Viewport; theme: Theme; fixture: string; reduced_motion: boolean }
export type Theme = "light" | "dark";
export type CheckState = "pending" | "current" | "stale" | "failed" | "unavailable";
export interface CheckResult { state: CheckState; coverage: Array<string>; failures: Array<string> }
export interface RenderReceipt { request: RenderRequest; source_hash: string; runtime_hash: string; policy_hash: string; screenshot: ArtifactRef; geometry: ArtifactRef; checks: Record<string, CheckResult> }
export interface QualityReport { revision: RevisionReference; source: CheckResult; render: CheckResult; interaction: CheckResult; accessibility: CheckResult; visual: CheckResult; assets: CheckResult; implementation: CheckResult; evidence: Array<ArtifactRef> }
export type DesignRequest = { operation: "list"; payload: {  } } | { operation: "create"; payload: { input: CreateDesign } } | { operation: "generate"; payload: { request: GenerationRequest } } | { operation: "draft_implementation"; payload: { request: DraftHandoff } } | { operation: "prepare_implementation"; payload: { request: HandoffRequest } } | { operation: "apply"; payload: { request: ApproveHandoff } } | { operation: "verify_implementation"; payload: { request: VerifyHandoff } } | { operation: "status"; payload: { artifact_id: ArtifactId } } | { operation: "read"; payload: { artifact_id: ArtifactId; revision: RevisionId } } | { operation: "read_binding"; payload: { artifact_id: ArtifactId; revision: RevisionId; node_id: NodeId } } | { operation: "verify"; payload: { artifact_id: ArtifactId } } | { operation: "render"; payload: { request: RenderRequest; operation_id: OperationId } } | { operation: "interact"; payload: { request: InteractionRequest } } | { operation: "capture"; payload: { artifact_id: ArtifactId; revision: RevisionId; artboard_id: ArtboardId; viewport: Viewport; offset: number; interaction_id: OperationId | null } } | { operation: "geometry"; payload: { artifact_id: ArtifactId; revision: RevisionId; artboard_id: ArtboardId; viewport: Viewport; interaction_id: OperationId | null } } | { operation: "edit"; payload: { edit: DesignEdit } } | { operation: "comment"; payload: { comment: DesignComment; operation_id: OperationId } } | { operation: "fork"; payload: { artifact_id: ArtifactId; revision: RevisionId; operation_id: OperationId } } | { operation: "restore"; payload: { artifact_id: ArtifactId; expected_revision: RevisionId; revision: RevisionId; operation_id: OperationId } } | { operation: "export"; payload: { request: ExportRequest } } | { operation: "accept"; payload: { request: AcceptRequest } } | { operation: "sync"; payload: { path: string; operation_id: OperationId } };
export type DesignCommand = { operation: "list";  } | { operation: "create"; input: CreateDesign } | { operation: "open"; artifact_id: ArtifactId } | { operation: "status"; artifact_id: ArtifactId } | { operation: "revise"; artifact_id: ArtifactId; brief: string; operation_id: OperationId } | { operation: "verify"; artifact_id: ArtifactId } | { operation: "fork"; artifact_id: ArtifactId; revision: RevisionId; operation_id: OperationId } | { operation: "restore"; artifact_id: ArtifactId; revision: RevisionId; operation_id: OperationId } | { operation: "export"; artifact_id: ArtifactId; revision: RevisionId; format: ExportFormat; destination: string; artboard_id: ArtboardId | null; viewport: Viewport | null } | { operation: "apply"; artifact_id: ArtifactId; revision: RevisionId } | { operation: "sync"; path: string };
export type ExportFormat = "source" | "png" | "html";
export interface ExportRequest { artifact_id: ArtifactId; revision: RevisionId; format: ExportFormat; destination: string; artboard_id: ArtboardId | null; viewport: Viewport | null; operation_id: OperationId }
export interface ExportReceipt { artifact_id: ArtifactId; revision: RevisionId; source_hash: string; manifest_hash: string; paths: Array<string>; omitted_assets: Array<string>; complete: boolean; warning: string | null }
export interface AcceptRequest { artifact_id: ArtifactId; revision: RevisionId; evidence_hash: string; acknowledged_incomplete: Array<string>; operation_id: OperationId }
export interface DesignFact { kind: string; name: string; value: string; path: string; source_hash: string; line: number; confidence: string }
export interface DesignSystemSnapshot { root: string; fingerprint: string; files: Record<string, string>; facts: Array<DesignFact>; unresolved: Array<string>; excluded: Array<string> }
export interface GenerationRequest { artifact_id: ArtifactId; expected_revision: RevisionId; brief: string; operation_id: OperationId }
export interface ConceptDirection { title: string; layout: string; typography: string; content_strategy: string }
export type RunPhase = "directions" | "generate" | "render" | "review" | "complete" | "blocked";
export interface RunProgress { phase: RunPhase; in_flight: boolean; repairs: number; deadline_ms: string }
export interface DesignRunState { request: GenerationRequest; request_hash: string; provider: string; model: string; effort: string; root_identity: string; context: ArtifactRef; profile: ArtifactRef; system_snapshot: ArtifactRef | null; directions: Array<ConceptDirection>; progress: RunProgress; reply: ArtifactRef | null; last_revision: RevisionId; findings: Array<string>; quality: QualityReport | null }
export interface HandoffRequest { artifact_id: ArtifactId; revision: RevisionId; patch: string; verification: Array<string>; operation_id: OperationId }
export interface ImplementationProposal { request: HandoffRequest; accepted: RevisionReference; acceptance_evidence_hash: string; target_snapshot: DesignSystemSnapshot; workspace_fingerprint: string; target_files: Array<string>; preview_transaction: string; before_hashes: Record<string, string | null>; proposed_hashes: Record<string, string | null>; plan_revision: string; plan_hash: string; step_id: string; brief: string }
export interface PreparedHandoff { proposal_hash: string; proposal: ImplementationProposal }
export interface ApproveHandoff { proposal_id: OperationId; proposal_hash: string; operation_id: OperationId }
export interface DraftHandoff { artifact_id: ArtifactId; revision: RevisionId; target_files: Array<string>; operation_id: OperationId }
export interface TargetBrowserCheck { process_id: number; port: number; path: string; actions: Array<TargetBrowserAction>; dom_contains: string; accessibility_contains: string }
export interface TargetBrowserAction { tool: string; args: unknown }
export interface VerifyHandoff { proposal_id: OperationId; proposal_hash: string; build_command: string; test_command: string; timeout_ms: number; browser: TargetBrowserCheck | null; operation_id: OperationId }
export type PrototypeSelector = { kind: "role"; role: string; name: string } | { kind: "label"; value: string } | { kind: "test_id"; value: string };
export type PrototypeAction = { action: "click"; selector: PrototypeSelector } | { action: "type"; selector: PrototypeSelector; text: string } | { action: "select"; selector: PrototypeSelector; value: string } | { action: "key"; key: string } | { action: "expect_text"; text: string };
export interface InteractionRequest { render: RenderRequest; actions: Array<PrototypeAction>; operation_id: OperationId }
export interface InteractionReceipt { request: InteractionRequest; capture: RenderReceipt }
