//! Opt-in real rust-analyzer compatibility verification.
use super::config::ServerOverride;
use super::*;
use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use std::sync::Arc;

fn rust_server() -> PathBuf {
    let path = PathBuf::from(
        std::env::var_os("DAVINCI_TEST_RUST_ANALYZER")
            .expect("DAVINCI_TEST_RUST_ANALYZER must name a provisioned rust-analyzer"),
    );
    assert!(path.is_absolute() && path.is_file(), "{path:?}");
    path
}

fn trusted(manager: &LanguageIntelligence) {
    let mut policy =
        davinci_agent::PermissionPolicy::new(davinci_agent::PermissionMode::AlwaysApprove);
    policy.project_trusted = true;
    manager.set_permissions(Some(Arc::new(davinci_agent::PermissionState::new(policy))));
}

fn call(manager: &LanguageIntelligence, name: &str, args: Value) -> Value {
    let result = manager.execute(name, &args).unwrap();
    if result.is_error {
        let details = result.details.unwrap_or(Value::Null);
        assert_eq!(
            details.pointer("/error/code").and_then(Value::as_str),
            Some("unsupported_method"),
            "{name}: {details}"
        );
        return details;
    }
    result.details.unwrap()
}

fn hash(path: &Path) -> Option<String> {
    use sha2::{Digest, Sha256};
    let bytes = std::fs::read(path).ok()?;
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    Some(format!("{:x}", hasher.finalize()))
}

#[test]
#[ignore = "requires a provisioned DAVINCI_TEST_RUST_ANALYZER"]
fn real_rust_lsp_semantics() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("macro_fixture/src")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nmembers=[\"macro_fixture\"]\nresolver=\"2\"\n\n[package]\nname=\"davinci_lsp_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n\n[dependencies]\nmacro_fixture={path=\"macro_fixture\"}\n",
    )
    .unwrap();
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"davinci_lsp_fixture\"\nversion = \"0.1.0\"\ndependencies = [\"macro_fixture\"]\n\n[[package]]\nname = \"macro_fixture\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("build.rs"),
        "fn main() { let _ = std::fs::write(\"build-script-ran\", \"ran\"); }\n",
    )
    .unwrap();
    std::fs::write(
        root.join("macro_fixture/Cargo.toml"),
        "[package]\nname=\"macro_fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n\n[lib]\nproc-macro=true\n",
    )
    .unwrap();
    std::fs::write(
        root.join("macro_fixture/src/lib.rs"),
        "use proc_macro::TokenStream;\n#[proc_macro]\npub fn sentinel(_: TokenStream) -> TokenStream { let _ = std::fs::write(\"proc-macro-ran\", \"ran\"); \"0u8\".parse().unwrap() }\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "pub trait Formatter { fn format(&self, input: &str) -> String; }\n\
pub struct Plain;\n\
impl Formatter for Plain { fn format(&self, input: &str) -> String { input.to_owned() } }\n\
pub fn render(value: &impl Formatter) -> String { value.format(\"hello\") }\n\
pub const MACRO_VALUE: u8 = macro_fixture::sentinel!();\n",
    )
    .unwrap();
    let lock_before = hash(&root.join("Cargo.lock"));
    let target = root.join("target");
    assert!(!target.exists());

    let mut config = LanguageIntelligenceConfig::default();
    config.rust.server = Some(ServerOverride {
        program: rust_server(),
        args: Vec::new(),
    });
    config.rust.request_timeout_ms = 30_000;
    config.rust.initialization_timeout_ms = 60_000;
    config.rust.cold_request_timeout_ms = 120_000;
    if let Some(path) = std::env::var_os("DAVINCI_TEST_RUST_SYSROOT") {
        config.rust.sysroot = Some(PathBuf::from(path));
    }
    if let Some(path) = std::env::var_os("DAVINCI_TEST_RUST_SRC") {
        config.rust.sysroot_src = Some(PathBuf::from(path));
    }

    let manager = LanguageIntelligence::new(root, config);
    trusted(&manager);
    let definition = call(
        &manager,
        "lsp_definition",
        json!({"path":"src/lib.rs","line":3,"column":7}),
    );
    if definition["available"] == true {
        assert!(definition["items"].as_array().unwrap().iter().any(|item| {
            item["path"] == "src/lib.rs" && item["range"]["start"]["line"] == 1
        }), "{definition}");
    }
    let references = call(
        &manager,
        "lsp_references",
        json!({"path":"src/lib.rs","line":1,"column":12,"includeDeclaration":true}),
    );
    if references["available"] == true {
        assert!(references["total"].as_u64().unwrap_or(0) >= 2, "{references}");
    }
    let hover = call(
        &manager,
        "lsp_hover",
        json!({"path":"src/lib.rs","line":1,"column":12}),
    );
    if hover["available"] == true {
        assert!(hover["text"].as_str().unwrap_or_default().contains("Formatter"));
    }
    let symbols = call(
        &manager,
        "lsp_document_symbols",
        json!({"path":"src/lib.rs"}),
    );
    if symbols["available"] == true {
        assert!(symbols["items"].as_array().unwrap().iter().any(|item| item["name"] == "Formatter"));
    }
    let workspace = call(
        &manager,
        "lsp_workspace_symbols",
        json!({"path":"src/lib.rs","query":"Formatter"}),
    );
    if workspace["available"] == true {
        assert!(workspace["total"].as_u64().unwrap_or(0) >= 1);
    }
    let implementations = call(
        &manager,
        "lsp_implementations",
        json!({"path":"src/lib.rs","line":1,"column":12}),
    );
    if implementations["available"] == true {
        assert!(implementations["total"].as_u64().unwrap_or(0) >= 1);
    }
    let _ = call(
        &manager,
        "lsp_type_definition",
        json!({"path":"src/lib.rs","line":4,"column":28}),
    );
    let diagnostics = call(
        &manager,
        "lsp_diagnostics",
        json!({"path":"src/lib.rs"}),
    );
    if diagnostics["available"] == true {
        assert_eq!(diagnostics["advisory"], true);
    }

    assert_eq!(hash(&root.join("Cargo.lock")), lock_before);
    assert!(!target.exists(), "analysis wrote into the project target directory");
    assert!(
        !root.join("build-script-ran").exists(),
        "navigation analysis executed the fixture build script"
    );
    assert!(
        !root.join("proc-macro-ran").exists()
            && !root.join("macro_fixture/proc-macro-ran").exists(),
        "navigation analysis executed the fixture proc macro"
    );
    manager.shutdown();
}
