[package]
name = "pi-protocol"
version = "0.84.4"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ciborium = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
