#!/usr/bin/env python3
"""Generate design wire declarations from the deliberately small Rust DTO grammar.

Unknown field types and unsupported enum shapes fail closed. --check is used in CI.
This generates declarations; Rust remains the request validation boundary.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "crates/davinci-coding-agent/src/design"
OUTPUT = ROOT / "crates/davinci-coding-agent/design-ui/src/contracts.generated.ts"


def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def split(text):
    result, start, depth = [], 0, 0
    for index, char in enumerate(text):
        if char in "<{([":
            depth += 1
        elif char in ">})]":
            depth -= 1
        elif char == "," and depth == 0:
            if text[start:index].strip():
                result.append(text[start:index].strip())
            start = index + 1
    if text[start:].strip():
        result.append(text[start:].strip())
    return result


def body(text, offset):
    depth = 1
    for end in range(offset + 1, len(text)):
        if text[end] == "{":
            depth += 1
        elif text[end] == "}":
            depth -= 1
        if depth == 0:
            return text[offset + 1:end]
    raise ValueError("Unbalanced declaration")


def generate():
    declarations = []
    names = {"RevisionId", "SchemaVersion"}
    types_source = (SOURCE / "types.rs").read_text()
    ids = [name.strip() for name in re.search(r"opaque_id!\(([^)]+)\)", types_source)[1].split(",") if name.strip()]
    names.update(ids)
    for filename in ["types.rs", "blob.rs", "records.rs", "controller.rs", "commands.rs", "export.rs", "acceptance.rs", "sync.rs", "generation.rs", "handoff.rs", "handoff_draft.rs", "interaction.rs"]:
        source = (SOURCE / filename).read_text()
        for match in re.finditer(r"pub (struct|enum) (\w+)\s*\{", source):
            kind, name = match.groups()
            if name in {"DesignLimits", "DesignController", "ConfinedRenderer"}:
                continue
            names.add(name)
            previous = source[:match.start()]
            attributes = previous[previous.rfind("#[derive"):]
            declarations.append((kind, name, body(source, match.end() - 1), attributes))

    def wire_type(value, attributes=""):
        value = value.strip()
        value = re.sub(r"super::(?:export|acceptance|sync|generation|handoff|handoff_draft|interaction)::", "", value)
        primitives = {"String": "string", "bool": "boolean", "u32": "number", "i64": "number", "serde_json::Value": "unknown"}
        if value == "u64":
            if not re.search(r'with\s*=\s*"decimal_u64"', attributes):
                raise ValueError("Browser-facing u64 needs decimal_u64")
            return "string"
        if value in primitives:
            return primitives[value]
        for prefix, transform in [
            ("Vec<", lambda inner: "Array<" + wire_type(inner) + ">"),
            ("Option<", lambda inner: wire_type(inner) + " | null"),
            ("BTreeMap<", lambda inner: "Record<" + ", ".join(wire_type(item) for item in split(inner)) + ">"),
        ]:
            if value.startswith(prefix) and value.endswith(">"):
                return transform(value[len(prefix):-1])
        if value not in names:
            raise ValueError("Unsupported type: " + value)
        return value

    def fields(contents):
        result = []
        for item in split(contents):
            attributes = " ".join(re.findall(r"#\[[^]]*\]", item))
            item = re.sub(r"#\[[^]]*\]", "", item).strip()
            match = re.fullmatch(r"(?:pub\s+)?(\w+)\s*:\s*(.+)", item, re.S)
            if not match:
                raise ValueError("Unsupported field: " + item)
            result.append(match[1] + ": " + wire_type(match[2], attributes))
        return "; ".join(result)

    lines = [
        "// Generated by scripts/design-contracts.py from Rust DTO declarations. Do not edit.",
        "export type SchemaVersion = 1;",
        "export type RevisionId = string;",
        *["export type " + name + " = string;" for name in ids],
    ]
    for kind, name, contents, attributes in declarations:
        if kind == "struct":
            lines.append("export interface " + name + " { " + fields(contents) + " }")
            continue
        tag = re.search(r'tag\s*=\s*"([^"]+)"', attributes)
        content = re.search(r'content\s*=\s*"([^"]+)"', attributes)
        variants = []
        for variant in split(contents):
            match = re.fullmatch(r"(\w+)\s*(?:\{(.*)\})?", variant, re.S)
            if not match:
                raise ValueError("Unsupported variant: " + variant)
            label = snake(match[1]) if re.search(r'rename_all\s*=\s*"snake_case"', attributes) else match[1]
            if tag:
                members = fields(match[2] or "")
                extra = (content[1] + ": { " + members + " }") if content else members
                variants.append('{ ' + tag[1] + ': "' + label + '"; ' + extra + ' }')
            else:
                if match[2] is not None:
                    raise ValueError("Untagged variant not supported")
                variants.append('"' + label + '"')
        lines.append("export type " + name + " = " + " | ".join(variants) + ";")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if OUTPUT.read_text() != result:
            raise SystemExit("Design TypeScript declarations are stale")
    else:
        OUTPUT.write_text(result, newline="\n")
